services:
  db:
    image: postgres:17-alpine
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hub
    ports:
      - "5432:5432"

  mailpit:
    image: axllent/mailpit
    ports:
      - "8025:8025"
      - "1025:1025"

  app:
    build: .
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/hub
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
