// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_500 from "./routes/_500.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $api_middleware from "./routes/api/_middleware.ts";
import * as $api_login from "./routes/api/login.ts";
import * as $api_logout from "./routes/api/logout.ts";
import * as $api_report_list from "./routes/api/report/list.ts";
import * as $api_reset from "./routes/api/reset.ts";
import * as $api_user from "./routes/api/user.ts";
import * as $attachment_id_ from "./routes/attachment/[id].ts";
import * as $change_password from "./routes/change-password.tsx";
import * as $contact from "./routes/contact.tsx";
import * as $forgot_password from "./routes/forgot-password.tsx";
import * as $imprint from "./routes/imprint.tsx";
import * as $index from "./routes/index.tsx";
import * as $login from "./routes/login.tsx";
import * as $logout from "./routes/logout.ts";
import * as $register from "./routes/register.tsx";
import * as $report_id_ from "./routes/report/[id].tsx";
import * as $report_id_comment from "./routes/report/[id]/comment.tsx";
import * as $report_id_edit from "./routes/report/[id]/edit.tsx";
import * as $report_id_edit_status from "./routes/report/[id]/edit/status.tsx";
import * as $report_index from "./routes/report/index.tsx";
import * as $report_new from "./routes/report/new.tsx";
import * as $reset_password from "./routes/reset-password.tsx";
import * as $users from "./routes/users.tsx";
import * as $verify from "./routes/verify.tsx";
import * as $Button from "./islands/Button.tsx";
import * as $ChangePasswordForm from "./islands/ChangePasswordForm.tsx";
import * as $CommentSection from "./islands/CommentSection.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $ForgotPasswordForm from "./islands/ForgotPasswordForm.tsx";
import * as $HeaderBar from "./islands/HeaderBar.tsx";
import * as $LoginForm from "./islands/LoginForm.tsx";
import * as $RegisterForm from "./islands/RegisterForm.tsx";
import * as $ReportDetailTabs from "./islands/ReportDetailTabs.tsx";
import * as $ReportEventItem from "./islands/ReportEventItem.tsx";
import * as $ReportForm from "./islands/ReportForm.tsx";
import * as $ReportTable from "./islands/ReportTable.tsx";
import * as $StatusDropdown from "./islands/StatusDropdown.tsx";
import * as $Table from "./islands/Table.tsx";
import * as $UserTable from "./islands/UserTable.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_500.tsx": $_500,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/_middleware.ts": $_middleware,
    "./routes/api/_middleware.ts": $api_middleware,
    "./routes/api/login.ts": $api_login,
    "./routes/api/logout.ts": $api_logout,
    "./routes/api/report/list.ts": $api_report_list,
    "./routes/api/reset.ts": $api_reset,
    "./routes/api/user.ts": $api_user,
    "./routes/attachment/[id].ts": $attachment_id_,
    "./routes/change-password.tsx": $change_password,
    "./routes/contact.tsx": $contact,
    "./routes/forgot-password.tsx": $forgot_password,
    "./routes/imprint.tsx": $imprint,
    "./routes/index.tsx": $index,
    "./routes/login.tsx": $login,
    "./routes/logout.ts": $logout,
    "./routes/register.tsx": $register,
    "./routes/report/[id].tsx": $report_id_,
    "./routes/report/[id]/comment.tsx": $report_id_comment,
    "./routes/report/[id]/edit.tsx": $report_id_edit,
    "./routes/report/[id]/edit/status.tsx": $report_id_edit_status,
    "./routes/report/index.tsx": $report_index,
    "./routes/report/new.tsx": $report_new,
    "./routes/reset-password.tsx": $reset_password,
    "./routes/users.tsx": $users,
    "./routes/verify.tsx": $verify,
  },
  islands: {
    "./islands/Button.tsx": $Button,
    "./islands/ChangePasswordForm.tsx": $ChangePasswordForm,
    "./islands/CommentSection.tsx": $CommentSection,
    "./islands/Counter.tsx": $Counter,
    "./islands/ForgotPasswordForm.tsx": $ForgotPasswordForm,
    "./islands/HeaderBar.tsx": $HeaderBar,
    "./islands/LoginForm.tsx": $LoginForm,
    "./islands/RegisterForm.tsx": $RegisterForm,
    "./islands/ReportDetailTabs.tsx": $ReportDetailTabs,
    "./islands/ReportEventItem.tsx": $ReportEventItem,
    "./islands/ReportForm.tsx": $ReportForm,
    "./islands/ReportTable.tsx": $ReportTable,
    "./islands/StatusDropdown.tsx": $StatusDropdown,
    "./islands/Table.tsx": $Table,
    "./islands/UserTable.tsx": $UserTable,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
